### ISSUE TITLE
??

### ISSUE THREAD

**Issue by Pers0n-dev** [zdc-dev/Chatutils#1]
You made non of these

**Comment by zdc54** [comment]
i just forked it thats all

**Comment by Pers0n-dev** [comment]
so this whole thing is forking other peoples things?

**Comment by zdc54** [comment]
It says that i forked it, clearly.

**Comment by zdc54** [comment]
I never said that i made it

**Comment by Pers0n-dev** [comment]
it not a fork

**Comment by Pers0n-dev** [comment]
https://github.com/Chatutils/Chatutils/network/members

**Comment by zdc54** [comment]
It is :linug:

**Comment by zdc54** [comment]
You forked chatutils smh

**Comment by zdc54** [comment]
Don't tell me not to fork stuff
